@host = http://localhost
@port = 8080
@baseURL = {{host}}:{{port}}

### success
POST {{baseURL}}/todos
Content-Type: application/json

{
  "header": "task",
  "description": "description"
}

### success
POST {{baseURL}}/todos
Content-Type: application/json

{
  "header": "task"
}

### invalid header
POST {{baseURL}}/todos
Content-Type: application/json

{
  "description": "description"
}

### invalid header
POST {{baseURL}}/todos
Content-Type: application/json

{
  "header": "",
  "description": "description"
}