@host = http://localhost
@port = 8080
@baseURL = {{host}}:{{port}}

### success
GET {{baseURL}}/todos/1
Content-Type: application/json

### invalid
GET {{baseURL}}/todos/r
Content-Type: application/json

