@host = http://localhost
@port = 8080
@baseURL = {{host}}:{{port}}

### success
PUT {{baseURL}}/todos/1
Content-Type: application/json

{
  "header": "task-1",
  "description": "description",
  "completed": true
}

### invalid
PUT {{baseURL}}/todos/tu
Content-Type: application/json

{
  "header": "task-1",
  "description": "description",
  "completed": true
}